INFO:root:2018-04-24 updated doc L'Ã‰ducation Sentimentale by: admin(librarian);
INFO:root: 2018-04-24 returned doc by: admin; User: gnomerDoc:Origin
ERROR:django.request:Internal Server Error: /requests/return/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/danilginzburg/Projects/innopolka/Documents/librarian_view.py", line 20, in inner
    return func(request, *args, **kwargs)
  File "/Users/danilginzburg/Projects/innopolka/BookRequests/views.py", line 189, in return_doc
    for user in req.users:
TypeError: 'ManyRelatedManager' object is not iterable
INFO:root: 2018-04-24 returned doc by: admin; User: gnomerDoc:Introducing Spyder, the Scientific PYthon Development EnviRonment
INFO:root:2018-04-24 updated user gnomer(librarian) by: admin(admin);
INFO:root:2018-04-24 updated user gnomer(librarian) by: admin(admin);
INFO:root:2018-04-24 updated user instructor_user(instructor) by: admin(admin);
INFO:root:2018-04-24 updated user instructor_user(instructor) by: admin(admin);
INFO:root:2018-04-24 approved request by: masha_admin; User: TA_userDoc:Origin
INFO:root:2018-04-24 canceled request by: masha_admin; User: TA_userDoc:L
